#!/bin/bash

echo "========================================="
echo "PDF Extraction Performance Test"
echo "========================================="
echo ""

# Display help for new features
echo "New Performance Features:"
echo "  • Concurrent PDF processing in batch mode"
echo "  • Result caching for repeated extractions"
echo "  • Optimized I/O with larger buffers"
echo "  • Command execution pooling"
echo "  • Detailed performance metrics"
echo "  • CPU and memory profiling support"
echo ""

# Show available commands
echo "Example Usage:"
echo ""
echo "1. Single PDF with benchmark metrics:"
echo "   ./swiper -file document.pdf -benchmark"
echo ""
echo "2. Batch processing with concurrent PDFs:"
echo "   ./swiper -dir /path/to/pdfs -output extracted -benchmark"
echo ""
echo "3. With CPU profiling:"
echo "   ./swiper -file document.pdf -profile cpu -benchmark"
echo ""
echo "4. With result caching enabled:"
echo "   ./swiper -file document.pdf -cache -benchmark"
echo ""
echo "5. Scan and copy PDFs:"
echo "   ./swiper -scan . -copydir pdf-collection"
echo ""
echo "========================================="
echo "Performance Optimizations Summary:"
echo "========================================="
echo ""
echo "✓ Concurrent PDF processing (2-4 PDFs simultaneously)"
echo "✓ Page-level result caching with in-memory cache"
echo "✓ Buffered I/O operations (32KB-256KB buffers)"
echo "✓ Command execution pooling with timeouts"
echo "✓ Async logging to prevent worker blocking"
echo "✓ Temp directory pooling and reuse"
echo "✓ Atomic counters for thread-safe metrics"
echo "✓ Parallel text and image extraction per page"
echo "✓ Optimized file copying with large buffers"
echo ""
echo "Expected Performance Gains:"
echo "  • 2-4x faster batch processing"
echo "  • 30-50% reduction in I/O overhead"
echo "  • Better CPU core utilization"
echo "  • Reduced memory allocations"
echo ""